# GENERATE TIME: Sun Apr 14 08:17:53 2024
# CMD:
# pyiqa/train.py -opt options/train/CLIPIQA/train_CLIPIQA_koniq10k.yml

# general settings
# name: debug_DBCNN_LIVEC
#name: 002_CLIPIQA_ViT-L14_KonIQ10k
name: 003_CLIPIQA_RN50_KonIQ10k
# name: debug_CLIPIQA
model_type: GeneralIQAModel
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 123

# dataset and data loader settings
datasets:
  train:
    name: koniq10k
    type: GeneralNRDataset
    #dataroot_target: ./datasets/koniq10k/512x384
    #meta_info_file: ./datasets/meta_info/meta_info_KonIQ10kDataset.csv
    dataroot_target: ./datasets/zdjecia_uczenie
    meta_info_file: ./datasets/meta_info/oceny_zdjec.csv
    #dataroot_target: ./datasets/zdjecia_uczenie_mini
    #meta_info_file: ./datasets/meta_info/oceny_zdjec_mini.csv
    #split_file: ./datasets/train_split_info/los10mini.pkl
    #dataroot_target: ./datasets/zdjecia_uczenie_g
    #meta_info_file: ./datasets/meta_info/oceny_zdjec_g.csv
    #split_file: ./datasets/train_split_info/los1g.pkl
    #split_file: ./datasets/train_split_info/koniq10k_official.pkl
    #dataroot_target: ./datasets/zdjecia_uczenie_2013baza
    #meta_info_file: ./datasets/meta_info/oceny_zdjec2013.csv
    #split_file: ./datasets/train_split_info/podzial_zbioru_tid2013_i.pkl
    #dataroot_target: ./datasets/zdjecia_uczenie2008
    #meta_info_file: ./datasets/meta_info/oceny_zdjec2008.csv
    #split_file: ./datasets/train_split_info/podzial_zbioru_tid2008_m.pkl
    #dataroot_target: ./datasets/zdjecia_uczenie_mdid
    #meta_info_file: ./datasets/meta_info/oceny_zdjec_mdid.csv
    #split_file: ./datasets/train_split_info/podzial_zbioru_mdid_m.pkl
    #dataroot_target: ./datasets/zdjecia_uczenie_challenge
    #meta_info_file: ./datasets/meta_info/oceny_zdjec_bazach.csv
    #split_file: ./datasets/train_split_info/podzial_zbioru_challenge_i.pkl
    #dataroot_target: ./datasets/zdjecia_uczenie_konikQ
    #meta_info_file: ./datasets/meta_info/oceny_zdjec_konikQ.csv
    #split_file: ./datasets/train_split_info/podzial_zbioru_konikq_i.pkl
    split_file: ./datasets/train_split_info/podzial_zbioru_moja_baza.pkl
    mos_max: 5

    augment:
      hflip: true
      random_crop: 384 
    img_range: 1

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: koniq10k
    type: GeneralNRDataset
    #dataroot_target: ./datasets/koniq10k/512x384
    #meta_info_file: ./datasets/meta_info/meta_info_KonIQ10kDataset.csv
    dataroot_target: ./datasets/zdjecia_uczenie
    meta_info_file: ./datasets/meta_info/oceny_zdjec.csv
    #dataroot_target: ./datasets/zdjecia_uczenie_mini
    #meta_info_file: ./datasets/meta_info/oceny_zdjec_mini.csv
    #split_file: ./datasets/train_split_info/los10mini.pkl
    #dataroot_target: ./datasets/zdjecia_uczenie_1024
    #eta_info_file: ./datasets/meta_info/oceny_zdjec_1024.csv
    #split_file: ./datasets/train_split_info/los2.pkl
    #dataroot_target: ./datasets/zdjecia_uczenie_g
    #meta_info_file: ./datasets/meta_info/oceny_zdjec_g.csv
    #split_file: ./datasets/train_split_info/los1g.pkl
    #split_file: ./datasets/train_split_info/koniq10k_official.pkl
    #dataroot_target: ./datasets/zdjecia_uczenie_2013baza
    #meta_info_file: ./datasets/meta_info/oceny_zdjec2013.csv
    #split_file: ./datasets/train_split_info/podzial_zbioru_tid2013_i.pkl
    #dataroot_target: ./datasets/zdjecia_uczenie2008
    #meta_info_file: ./datasets/meta_info/oceny_zdjec2008.csv
    #split_file: ./datasets/train_split_info/podzial_zbioru_tid2008_m.pkl
    #dataroot_target: ./datasets/zdjecia_uczenie_mdid
    #meta_info_file: ./datasets/meta_info/oceny_zdjec_mdid.csv
    #split_file: ./datasets/train_split_info/podzial_zbioru_mdid_m.pkl
    #dataroot_target: ./datasets/zdjecia_uczenie_challenge
    #meta_info_file: ./datasets/meta_info/oceny_zdjec_bazach.csv
    #split_file: ./datasets/train_split_info/podzial_zbioru_challenge_i.pkl
    #dataroot_target: ./datasets/zdjecia_uczenie_konikQ
    #meta_info_file: ./datasets/meta_info/oceny_zdjec_konikQ.csv
    #split_file: ./datasets/train_split_info/podzial_zbioru_konikq_i.pkl
    split_file: ./datasets/train_split_info/podzial_zbioru_moja_baza.pkl
    mos_max: 5

    num_worker_per_gpu: 4
    batch_size_per_gpu: 1

    # augment:
    #   center_crop: 384

# network structures
network:
  type: CLIPIQA 
  model_type: clipiqa+
  # backbone: ViT-L/14
  backbone: RN50
  pretrained: false
  #pretrained: true
  pos_embedding: true

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim:
    type: Adam 
    lr: !!float 2e-3
  
  scheduler:
    type: CosineAnnealingLR
    T_max: 50 
    eta_min: 0

  total_iter: 2000000
  total_epoch: 50
  warmup_iter: -1  # no warm up

  # losses
  mos_loss_opt:
    type: MSELoss
    loss_weight: !!float 1.0

  metric_loss_opt:
    type: PLCCLoss
    loss_weight: !!float 1.0

# validation settings
val:
  val_freq: !!float 500
  save_img: false
  pbar: true

  key_metric: srcc # if this metric improve, update all metrics. If not specified, each best metric results will be updated separately
  metrics:
    srcc:
      type: calculate_srcc

    plcc:
      type: calculate_plcc

# logging settings
logger:
  print_freq: 100
  save_latest_freq: !!float 1e3 
  log_imgs_freq: 1000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: True
